# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Apache Project configurations
#

# settings common across all supported platforms

name: Apache Bahir
short_name: Bahir
unix_name: bahir
description: Apache Bahir provides extensions to distributed analytic platforms such as Apache Spark and Apache Flink.

dev_list: dev@bahir.apache.org
dev_list_subscribe: dev-subscribe@bahir.apache.org
dev_list_unsubscribe: dev-unsubscribe@bahir.apache.org
dev_list_archive: https://mail-archives.apache.org/mod_mbox/bahir-dev/
dev_list_archive_mailarchive: https://www.mail-archive.com/dev@bahir.apache.org/
dev_list_archive_markmail:

user_list: user@bahir.apache.org
user_list_subscribe: user-subscribe@bahir.apache.org
user_list_unsubscribe: user-unsubscribe@bahir.apache.org
user_list_archive: https://mail-archives.apache.org/mod_mbox/bahir-user/
user_list_archive_mailarchive: https://www.mail-archive.com/user@bahir.apache.org/
user_list_archive_markmail:

commits_list: commits@bahir.apache.org
commits_list_subscribe: commits-subscribe@bahir.apache.org
commits_list_unsubscribe: commits-unsubscribe@bahir.apache.org
commits_list_archive: https://mail-archives.apache.org/mod_mbox/bahir-commits/
commits_list_archive_mailarchive: https://www.mail-archive.com/commits@bahir.apache.org/
commits_list_archive_markmail:

jira: BAHIR

website_repository: https://gitbox.apache.org/repos/asf/bahir-website.git
website_repository_mirror: https://github.com/apache/bahir-website

podling: false

# settings specific to supported platforms

# Apache Spark

spark_unix_name: bahir
spark_github_project_name: bahir

spark_latest_release: 2.3.3
spark_latest_release_date: 05/27/2019
spark_latest_release_location: https://www.apache.org/dist/bahir/bahir-spark
spark_latest_release_location_mirror: https://www.apache.org/dyn/closer.lua/bahir/bahir-spark
spark_download: /downloads/spark

spark_source_repository: https://gitbox.apache.org/repos/asf/bahir.git
spark_source_repository_mirror: https://github.com/apache/bahir

# Apache Flink

flink_unix_name: bahir-flink
flink_github_project_name: bahir-flink

flink_latest_release: 1.0
flink_latest_release_date: 05/24/2017
flink_latest_release_location: https://www.apache.org/dist/bahir/bahir-flink
flink_latest_release_location_mirror: https://www.apache.org/dyn/closer.lua/bahir/bahir-flink
flink_download: /downloads/flink


flink_source_repository: https://gitbox.apache.org/repos/asf/bahir-flink.git
flink_source_repository_mirror: https://github.com/apache/bahir-flink

# Website

website_source_repository: https://gitbox.apache.org/repos/asf/bahir-website.git
website_source_repository_mirror: https://github.com/apache/bahir-website
